version: '3.3'
services:
  db:
    image: postgres:10-alpine
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app_db
    ports:
      - "5432"
  django:
    build:
      context: .
      args:
        - REQUIREMENTS=development.txt
    command:  /code/run/run_dev.sh
    volumes:
      - ./:/code
    working_dir: /code/
    env_file: ./docker/Enviroment
    ports:
      - "8008:8008"
    links:
      - db
    depends_on:
      - db